name: Issue Commenter
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create a test comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: This is a test comment from the simplified workflow.
          token: ${{ secrets.GITHUB_TOKEN }}
