name: Comment on New Issues

on:
  issues:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment for bug
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you. We will fix it. Best regards, sieun-hcs.'
            })
      - name: Add comment for feature
        if: contains(github.event.issue.labels.*.name, 'feature')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you, we will consider to include this feature. Best regards, sieun-hcs.'
            })
      - name: Add comment for discussion
        if: contains(github.event.issue.labels.*.name, 'discussion')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Happy to discuss this topic with you. Best regards, sieun-hcs.'
            })
